# Generated by Django 4.2.23 on 2025-09-05 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.CharField(choices=[('UK', 'United Kingdom'), ('USA', 'United States'), ('CANADA', 'Canada'), ('SCHENGEN', 'Schengen'), ('QATAR', 'Qatar'), ('DUBAI', 'Dubai')], max_length=20)),
                ('visa_type', models.CharField(choices=[('TOURIST', 'Tourist Visa'), ('STUDENT', 'Student Visa'), ('WORK', 'Work Visa'), ('BUSINESS', 'Business Visa'), ('TRANSIT', 'Transit Visa'), ('RESIDENCY', 'Residency / PR'), ('DIPLOMATIC', 'Diplomatic Visa'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DOCUMENTS SUBMITTED', 'Documents Submitted'), ('QUEUED', 'Queued'), ('ASSIGNED', 'Assigned to Officer'), ('UNDER REVIEW', 'Under Review'), ('FORM FILLED', 'Form Filled'), ('ADMIN REVIEW', 'Admin Review'), ('SUBMITTED', 'Submitted to Embassy'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='QUEUED', max_length=20)),
                ('form_data', models.JSONField(blank=True, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('reference_no', models.CharField(max_length=50, unique=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_applications', to='Accounts.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmbassySubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('submitted_by', models.CharField(max_length=255)),
                ('submission_channel', models.CharField(max_length=50)),
                ('submission_date', models.DateField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='Applications.visaapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('decision_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=50)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='Applications.visaapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='visaapplication',
            index=models.Index(fields=['reference_no', 'status'], name='Application_referen_d459f3_idx'),
        ),
    ]
