# Generated by Django 4.2.23 on 2025-10-03 04:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.CharField(choices=[('UK', 'United Kingdom'), ('USA', 'United States'), ('CANADA', 'Canada'), ('SCHENGEN', 'Schengen'), ('QATAR', 'Qatar'), ('DUBAI', 'Dubai')], max_length=20)),
                ('visa_type', models.CharField(choices=[('TOURIST', 'Tourist Visa'), ('STUDENT', 'Student Visa'), ('WORK', 'Work Visa'), ('BUSINESS', 'Business Visa'), ('TRANSIT', 'Transit Visa'), ('RESIDENCY', 'Residency / PR'), ('DIPLOMATIC', 'Diplomatic Visa'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('INITIATED', 'Initiated by Officer'), ('ASSIGNED', 'Assigned to Officer'), ('REVIEWED', 'Reviewed'), ('FORM FILLED', 'Form Filled'), ('ADMIN REVIEW', 'Admin Review'), ('SUBMITTED', 'Awaiting Embassy Decision'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='QUEUED', max_length=20)),
                ('form_data', models.JSONField(blank=True, null=True)),
                ('visa_application_url', models.URLField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('reference_no', models.CharField(max_length=50, unique=True)),
                ('rejection_letter', models.FileField(blank=True, null=True, upload_to='rejection_letters/')),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to='Accounts.staffprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_applications', to='Accounts.clientprofile')),
                ('created_by_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_applications', to='Accounts.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousRefusalLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='refusal_letters/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refusal_letters', to='Applications.visaapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmbassySubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('submitted_by', models.CharField(max_length=255)),
                ('submission_channel', models.CharField(max_length=50)),
                ('review_date', models.DateTimeField()),
                ('submission_date', models.DateTimeField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='Applications.visaapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_reviewer', to='Accounts.staffprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('decision_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=50)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='Applications.visaapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='visaapplication',
            index=models.Index(fields=['reference_no', 'status'], name='Application_referen_d459f3_idx'),
        ),
    ]
