# Generated by Django 4.2.23 on 2025-10-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='country',
            field=models.CharField(choices=[('UK', 'United Kingdom'), ('USA', 'United States'), ('CANADA', 'Canada'), ('FRANCE', 'France'), ('QATAR', 'Qatar'), ('DUBAI', 'Dubai'), ('SOUTH AFRICA', 'South Africa')], max_length=20),
        ),
    ]
