# Generated by Django 4.2.23 on 2025-09-12 02:39

import Applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='reference_no',
            field=models.CharField(default=Applications.models.default_reference_no, editable=False, max_length=50, unique=True),
        ),
    ]
