# Generated by Django 4.2.23 on 2025-09-12 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Applications', '0002_alter_visaapplication_reference_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to='Accounts.staffprofile'),
        ),
    ]
