# Generated by Django 4.2.23 on 2025-10-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0002_alter_visaapplication_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='visa_type',
            field=models.CharField(choices=[('TOURIST - EMPLOYED', 'Tourist Visa - Employed'), ('TOURIST - SELF EMPLOYED', 'Tourist Visa - Self Employed'), ('STUDENT', 'Student Visa'), ('WORK', 'Work Visa'), ('BUSINESS', 'Business Visa'), ('TRANSIT', 'Transit Visa'), ('RESIDENCY', 'Residency / PR'), ('DIPLOMATIC', 'Diplomatic Visa'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
