# Generated by Django 4.2.23 on 2026-01-22 12:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Applications', '0003_alter_visaapplication_visa_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('OFFER_RECEIVED', 'Offer Received'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CASApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cas_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CAS_ISSUED', 'CAS Issued'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('cas_letter', models.FileField(blank=True, null=True, upload_to='cas_letters/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentApplicationPipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.CharField(choices=[('UK', 'United Kingdom'), ('USA', 'United States'), ('CANADA', 'Canada'), ('FRANCE', 'France'), ('QATAR', 'Qatar'), ('DUBAI', 'Dubai'), ('SOUTH AFRICA', 'South Africa')], max_length=20)),
                ('current_stage', models.CharField(choices=[('ADMISSION', 'Admission Application'), ('CAS', 'CAS Processing'), ('VISA', 'Student Visa Application'), ('COMPLETED', 'Completed')], default='ADMISSION', max_length=20)),
                ('admission_application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Applications.admissionapplication')),
                ('cas_application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Applications.casapplication')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.clientprofile')),
                ('visa_application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Applications.visaapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='casapplication',
            name='pipeline',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Applications.studentapplicationpipeline'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='pipeline',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Applications.studentapplicationpipeline'),
        ),
    ]
