# Generated by Django 4.2.23 on 2025-09-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0003_alter_visaapplication_assigned_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='reference_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
