# Generated by Django 4.2.23 on 2026-01-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0004_admissionapplication_casapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('stage', models.CharField(choices=[('ADMISSION', 'Admission'), ('CAS', 'CAS'), ('VISA', 'Visa')], max_length=20)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('country', 'stage')},
            },
        ),
    ]
