# Generated by Django 4.2.23 on 2025-09-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0004_alter_visaapplication_reference_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('ASSIGNED', 'Assigned to Officer'), ('UNDER REVIEW', 'Under Review'), ('FORM FILLED', 'Form Filled'), ('ADMIN REVIEW', 'Admin Review'), ('SUBMITTED', 'Submitted to Embassy'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='QUEUED', max_length=20),
        ),
    ]
