# Generated by Django 4.2.23 on 2026-01-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0005_stagedefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='current_stage',
            field=models.CharField(default='ADMISSION', max_length=20),
        ),
    ]
