# Generated by Django 4.2.23 on 2026-01-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0006_visaapplication_current_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='current_stage',
            field=models.CharField(choices=[('ADMISSION', 'Admission'), ('CAS', 'CAS'), ('VISA', 'Visa')], default='ADMISSION', max_length=20),
        ),
    ]
