# Generated by Django 4.2.23 on 2026-01-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0007_visaapplication_progress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visaapplication',
            old_name='current_stage',
            new_name='stage',
        ),
    ]
