# Generated by Django 4.2.23 on 2025-09-18 18:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_user_role'),
        ('Applications', '0007_alter_visaapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='embassysubmission',
            name='review_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='embassysubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_reviewer', to='Accounts.staffprofile'),
        ),
        migrations.AlterField(
            model_name='embassysubmission',
            name='submission_date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='FormProcessing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('application_url', models.URLField()),
                ('visa_username', models.CharField(max_length=255)),
                ('visa_password', models.CharField(max_length=255)),
                ('pdf_copy', models.FileField(blank=True, help_text='Upload a PDF copy of the filled visa form', null=True, upload_to='visa_forms/')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_processing', to='Applications.visaapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
