# Generated by Django 4.2.23 on 2026-02-03 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0008_rename_current_stage_visaapplication_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rejection_letters/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_letters', to='Applications.visaapplication')),
            ],
        ),
    ]
