# Generated by Django 4.2.23 on 2025-09-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0008_embassysubmission_review_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formprocessing',
            old_name='pdf_copy',
            new_name='pdf_form',
        ),
    ]
