# Generated by Django 4.2.23 on 2025-09-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0009_rename_pdf_copy_formprocessing_pdf_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formprocessing',
            old_name='pdf_form',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='formprocessing',
            old_name='visa_password',
            new_name='visa_application_password',
        ),
        migrations.RenameField(
            model_name='formprocessing',
            old_name='visa_username',
            new_name='visa_application_username',
        ),
    ]
