# Generated by Django 4.2.23 on 2025-09-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0010_rename_pdf_form_formprocessing_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='application_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
