# Adds the client-visibility gate for finalized (APPROVED/REJECTED)
# applications:
#   - client_notified: False until Admin clicks "Notify Client" on the
#     Admin dashboard's Finalized Applications list. Until then,
#     client-facing serializers cap the visible status at "SUBMITTED"
#     ("Awaiting Embassy Decision") - see
#     Applications.serializers.VisaApplicationSerializer.to_representation
#     and VisaApplicationDetailSerializer.to_representation.
#   - notified_by / client_notified_at: who notified the client, and when -
#     set by Applications.api_views.NotifyClientAPIView.
# Generated by Django 4.2.23 on 2026-09-21 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Applications', '0011_add_admin_validation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='client_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='client_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='notified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notified_applications', to='Accounts.staffprofile'),
        ),
    ]
