# Generated by Django 4.2.23 on 2025-09-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0011_visaapplication_application_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visaapplication',
            old_name='application_url',
            new_name='visa_application_url',
        ),
    ]
