# Generated by Django 4.2.23 on 2025-09-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0012_rename_application_url_visaapplication_visa_application_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormProcessing',
        ),
    ]
