# Generated by Django 4.2.23 on 2025-09-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0013_delete_formprocessing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('INITIATED', 'Initiated by Officer'), ('ASSIGNED', 'Assigned to Officer'), ('REVIEWED', 'Reviewed'), ('FORM FILLED', 'Form Filled'), ('ADMIN REVIEW', 'Admin Review'), ('SUBMITTED', 'Awaiting Embassy Decision'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='QUEUED', max_length=20),
        ),
    ]
