# Generated by Django 4.2.23 on 2025-09-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0014_alter_visaapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
