# Generated by Django 4.2.23 on 2025-09-29 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_user_must_reset_password'),
        ('Applications', '0015_alter_visaapplication_decision_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='created_by_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_applications', to='Accounts.staffprofile'),
        ),
    ]
