# Generated by Django 4.2.23 on 2025-09-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Case Officer', 'Case Officer'), ('Finance', 'Finance'), ('Support', 'Support'), ('Client', 'Client')], default='Client', max_length=20),
        ),
    ]
