# Generated by Django 4.2.23 on 2025-10-03 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.CharField(choices=[('UK', 'United Kingdom'), ('USA', 'United States'), ('CANADA', 'Canada'), ('SCHENGEN', 'Schengen'), ('QATAR', 'Qatar'), ('DUBAI', 'Dubai')], max_length=20)),
                ('visa_type', models.CharField(choices=[('TOURIST', 'Tourist Visa'), ('STUDENT', 'Student Visa'), ('WORK', 'Work Visa'), ('BUSINESS', 'Business Visa'), ('TRANSIT', 'Transit Visa'), ('RESIDENCY', 'Residency / PR'), ('DIPLOMATIC', 'Diplomatic Visa'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('IDENTITY', 'Identity Document'), ('FINANCIAL', 'Financial Document'), ('EMPLOYMENT', 'Employment Document'), ('ADMISSION', 'Admission Document'), ('FAMILY', 'Family/Dependent Document'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(choices=[('MISSING', 'Missing'), ('UPLOADED', 'Uploaded'), ('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('REJECTED', 'Rejected')], default='MISSING', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Applications.visaapplication')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Documents.documentrequirement')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
