# Generated by Django 4.2.23 on 2025-09-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequirement',
            name='category',
            field=models.CharField(choices=[('IDENTITY', 'Identity Document'), ('FINANCIAL', 'Financial Document'), ('EMPLOYMENT', 'Employment Document'), ('ADMISSION', 'Admission Document'), ('FAMILY', 'Family/Dependent Document'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
