# Generated by Django 4.2.23 on 2025-10-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequirement',
            name='country',
            field=models.CharField(choices=[('UK', 'United Kingdom'), ('USA', 'United States'), ('CANADA', 'Canada'), ('FRANCE', 'France'), ('QATAR', 'Qatar'), ('DUBAI', 'Dubai'), ('SOUTH AFRICA', 'South Africa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentrequirement',
            name='visa_type',
            field=models.CharField(choices=[('TOURIST - EMPLOYED', 'Tourist Visa - Employed'), ('TOURIST - SELF EMPLOYED', 'Tourist Visa - Self Employed'), ('STUDENT', 'Student Visa'), ('WORK', 'Work Visa'), ('BUSINESS', 'Business Visa'), ('TRANSIT', 'Transit Visa'), ('RESIDENCY', 'Residency / PR'), ('DIPLOMATIC', 'Diplomatic Visa'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
