# Generated by Django 4.2.23 on 2025-10-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_alter_documentrequirement_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequirement',
            name='form_file',
            field=models.FileField(blank=True, help_text='Optional PDF form to download or fill for this requirement.', null=True, upload_to='visa_forms/'),
        ),
    ]
