# Generated by Django 4.2.23 on 2025-09-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_alter_documentrequirement_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
    ]
