# Generated by Django 4.2.23 on 2025-10-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_documentrequirement_form_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequirement',
            name='form_file',
            field=models.FileField(blank=True, help_text='Optional PDF form to download or fill for this requirement.', null=True, upload_to='pdf_forms/'),
        ),
    ]
