# Generated by Django 4.2.23 on 2025-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_alter_document_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('UPLODED', 'Uploaded'), ('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('REJECTED', 'Rejected')], default='MISSING', max_length=10),
        ),
    ]
