# Generated by Django 4.2.23 on 2025-09-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0004_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('UPLOADED', 'Uploaded'), ('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('REJECTED', 'Rejected')], default='MISSING', max_length=10),
        ),
    ]
