# Generated by Django 4.2.23 on 2026-01-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0004_alter_documentrequirement_form_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequirement',
            name='stage',
            field=models.CharField(choices=[('ADMISSION', 'Admission'), ('CAS', 'CAS'), ('VISA', 'Visa')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
