 # Generated by Django 4.2.23 on 2026-01-22 21:30

from django.db import migrations

def seed_student_requirements(apps, schema_editor):
    DocumentRequirement = apps.get_model("Documents", "DocumentRequirement")
    COUNTRIES = ["UK", "CANADA", "USA"]

    
    VISA_TYPE = "STUDENT"

    DATA = {
        "ADMISSION": [
            ("International Passport (Bio-data page)", "Passport bio-data page"),
            ("Academic Qualifications", "WAEC / NECO / Degree / Transcript"),
            ("Curriculum Vitae (CV)", "Recent CV or résumé"),
            ("Statement of Purpose (SOP)", "Why you want to study this course"),
            ("Reference Letters", "Two academic or professional references"),
            ("English Language Proof", "IELTS / TOEFL / WAEC English"),
            ("Application Form Evidence", "School application submission"),
            ("Portfolio", "For creative courses only"),
        ],

        "CAS": [
            ("Valid International Passport", "Must be valid"),
            ("Unconditional Offer Letter", "Issued by school"),
            ("Tuition Fee Payment Proof", "Receipt or confirmation"),
            ("Proof of Funds", "28 consecutive days bank statement"),
            ("Sponsor Documents", "If sponsored"),
            ("TB Test Certificate", "IOM approved clinic"),
            ("Previous Academic Documents", "Certificates and transcripts"),
            ("CAS Payment Receipt", "If required"),
            ("Interview Readiness", "Credibility interview checklist"),
        ],

        "VISA": [
            ("Valid International Passport", "At least 6 months validity"),
            ("Offer Letter", "Admission letter"),
            ("Tuition Fee Payment Proof", "Paid fees"),
            ("Proof of Funds", "Financial statements"),
            ("CAS Letter", "Issued by university"),
            ("Medical / TB Certificate", "If required"),
            ("Visa Application Form", "Completed online"),
            ("Passport Photograph", "Embassy specification"),
            ("Academic Documents", "Certificates and transcripts"),
            ("Police Clearance Certificate", "If required"),
            ("Travel History", "Previous visas"),
            ("Accommodation Proof", "Hostel or tenancy"),
            ("Study Plan", "Career alignment"),
            ("Statement of Purpose", "Academic motivation"),
            ("Reference Letters", "Academic or professional"),
            ("English Language Proof", "IELTS / TOEFL / WAEC"),
            ("Curriculum Vitae", "If applicable"),
        ],
    }

    for country in COUNTRIES:
        for stage, items in DATA.items():
            for name, desc in items:
                DocumentRequirement.objects.get_or_create(
                    country=COUNTRY,
                    visa_type=VISA_TYPE,
                    stage=stage,
                    name=name,
                    defaults={
                        "description": desc,
                        "is_mandatory": True,
                    }
                )




    

def reverse_seed(apps, schema_editor):
    DocumentRequirement = apps.get_model("Documents", "DocumentRequirement")
    DocumentRequirement.objects.filter(visa_type="STUDENT").delete()

class Migration(migrations.Migration):

    dependencies = [
        ("Documents", "0005_documentrequirement_stage"),
    ]

    operations = [
        migrations.RunPython(seed_student_requirements, reverse_seed),
    ]

