# Generated by Django 4.2.23 on 2026-01-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0006_seed_student_requirements'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentrequirement',
            unique_together={('country', 'visa_type', 'stage', 'name')},
        ),
    ]
