# Generated by Django 4.2.23 on 2026-01-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0007_alter_documentrequirement_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentrequirement',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='documentrequirement',
            constraint=models.UniqueConstraint(fields=('country', 'visa_type', 'stage', 'name'), name='unique_requirement_per_stage'),
        ),
    ]
