# Generated by Django 4.2.23 on 2026-05-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0009_alter_documentrequirement_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequirement',
            name='country',
            field=models.CharField(choices=[('UK', 'United Kingdom'), ('USA', 'United States'), ('CANADA', 'Canada'), ('FRANCE', 'France'), ('QATAR', 'Qatar'), ('DUBAI', 'Dubai'), ('SOUTH AFRICA', 'South Africa'), ('SCHENGEN', 'Schengen')], max_length=20),
        ),
    ]
