# Generated by Django 4.2.23 on 2025-09-12 02:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Applications', '0002_alter_visaapplication_reference_no'),
        ('CaseManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReassignmentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('strategy', models.CharField(choices=[('manual', 'Manual'), ('bulk', 'Bulk'), ('auto-round-robin', 'Auto Round Robin'), ('auto-workload', 'Auto Workload')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignment_history', to='Applications.visaapplication')),
                ('from_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments_from', to='Accounts.staffprofile')),
                ('reassigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments_done', to='Accounts.staffprofile')),
                ('to_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments_to', to='Accounts.staffprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ReassignmentHistory',
        ),
    ]
