# Generated by Django 4.2.23 on 2025-09-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseManagement', '0002_reassignmentlog_delete_reassignmenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
